# [START runtime]
runtime: nodejs10
handlers:
  - url: /
    upload: dist/hivenews/index.html
    secure: always
    static_files: dist/hivenews/index.html
    redirect_http_response_code: 301
  - url: /
    static_dir: dist/hivenews/
# [END runtime]
