# [START runtime]
runtime: nodejs12
handlers:
  - url: /
    upload: dist/hive-institute/browser/index.html
    secure: always
    static_files: dist/hive-institute/browser/index.html
    redirect_http_response_code: 301
  - url: /
    static_dir: dist/hive-institute/browser/
# [END runtime]
